### ISSUE TITLE
neither exe nor jar will open

### ISSUE THREAD

**Issue by danbjor** [hube12/PigSpawnerFinder#1]
exe opens the command window and instantly closes, jar is unresponsive

**Comment by hube12** [comment]
Hi, Can you open a shell (shift + right click in the folder where you downloaded the jar or exe then open Powershell or open command prompt)? Then type `java -jar <File>.jar` or `./<File>.exe`
If you typed correctly the command (with the appropriate name) you will likely have an error saying you don't have Java installed. Please Install java https://www.java.com/fr/download/ . Follow this guide if you don't know how : https://www.java.com/en/download/help/download_options.html

**Comment by hube12** [comment]
Also be sure to not run a 32 bit OS nor having less than 1GB of ram

**Comment by danbjor** [comment]
Oop, alright it works. You didn't mention at all in the readme that you need to use powershell to open it :/
