### ISSUE TITLE
How to search an entire world for Pig Spawners?

### ISSUE THREAD

**Issue by ClancyDog1** [hube12/PigSpawnerFinder#2]
I'm trying to search my entire Minecraft world for Pig Spawners (meaning searching every chunk within the 30 million world border). It seems like it will take my PC about a week to search the world, but I'm not able to view the output history in Windows Console for output that is more than a few hundred lines earlier, meaning that I can't Control+F to find "Step 3" and see if my world has any pig spawners after the program has searched every spawner in the world because I can only search the previous few hundred lines.

How can I display every line of output or how I can search output that isn't displayed in the Console? I tried typing commands but I was unable to type any while the program was running.

**Comment by Takato65** [comment]
if you use power shell you can send the output to a file like so: `.\PigSpawnerFinder-1.0.0.exe | tee output.txt`

![image](https://user-images.githubusercontent.com/1214971/118388185-85659800-b5e8-11eb-9ace-581c679fb63c.png)

this will show up like so

![image](https://user-images.githubusercontent.com/1214971/118388422-f194cb80-b5e9-11eb-8dda-c0139be3f104.png)

**Comment by ClancyDog1** [comment]
That worked perfectly! I'm kinda a noob with coding, but your directions were so clear, helpful, and easy to follow. Thanks so much!
